#!/bin/sh

if [ x"$DEBIAN_VERSION" = x ]; then
	DEBIAN_VERSION="wheezy" # current stable
fi

STAGE3_VERSION=`date +'%Y-%W'`
STAGE3_FILE="/home/vps/distro/data/debian/${DEBIAN_VERSION}_${STAGE3_VERSION}.tar.bz2"

if [ ! -f "$STAGE3_FILE" ]; then
	# let's create a stage3
	TMP=`uuidgen`
	mkdir "/tmp/${TMP}"
	/usr/sbin/debootstrap --include=openssh-server,grub-legacy,linux-image-2.6-amd64 "${DEBIAN_VERSION}" "/tmp/${TMP}" http://ftp.jp.debian.org/debian/ >"/tmp/${TMP}.log" 2>&1
	( cd "/tmp/${TMP}"; tar cjpf "/tmp/${TMP}.tar.bz2" . )
	rm -fr "/tmp/${TMP}"
	mv -f "/tmp/${TMP}.tar.bz2" "$STAGE3_FILE"
	mv -f "/tmp/${TMP}.log" "${STAGE3_FILE}.log"
fi

tar xjpf "$STAGE3_FILE" -C "${TARGET}" 

echo '[5/10] Configuring OS...'

# fstab
echo "/dev/sda1		/boot	ext2	noauto,noatime	1 2" >>"${TARGET}/etc/fstab"
echo "/dev/sda3		/	ext2	noatime		0 1" >>"${TARGET}/etc/fstab"
echo "/dev/sda2		none	swap	noatime		0 0" >>"${TARGET}/etc/fstab"

# configure
if [ x"$CFG_NET_IP" != x ]; then
	echo >>"${TARGET}/etc/network/interfaces"
	echo "auto eth0" >>"${TARGET}/etc/network/interfaces"
	echo "iface eth0 inet static" >>"${TARGET}/etc/network/interfaces"
	echo -e "\taddress ${CFG_NET_IP}" >>"${TARGET}/etc/network/interfaces"
	echo -e "\tnetmask ${CFG_NET_MASK}" >>"${TARGET}/etc/network/interfaces"
	echo -e "\tgateway ${CFG_NET_GATEWAY}" >>"${TARGET}/etc/network/interfaces"
	echo "# Generated by forever.net" >"${TARGET}/etc/resolv.conf"
	for foo in $CFG_NET_DNS; do
		echo "nameserver ${foo}" >>"${TARGET}/etc/resolv.conf"
	done
fi

if [ x"$CFG_PASSWORD" != x ]; then
	# edit /etc/shadow, replace root line with root:$password:16075:0:99999:7:::
	sed -i 's#root:.*#root:'"${CFG_PASSWORD}"':16075:0:99999:7:::#' "${TARGET}/etc/shadow"
fi

# add grub

# let's try to do grub
echo "chroot . /bin/sh -c \"mount /boot && grub-install '(hd0)' && update-grub && umount /boot && sed -i 's/sda/vda/' /etc/fstab\"" >"${TARGET}/autorun.sh"
chmod +x "${TARGET}/autorun.sh"
#chroot "${TARGET}" grub-install "${DEVICE}"
#chroot "${TARGET}" grub-install --target=i386-pc "${DEVICE}"

